spring:
  application:
    name: gateway-service-parcial
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
        - id: movie-service-route
          uri: lb://movies-service
          predicates:
            - Path=/movies/**
        - id: movie-catalog-service-route
          uri: lb://movie-catalog-service
          predicates:
            - Path=/catalog/**
server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      deffaultZone: http://localhost:8761/eureka
  instance:
    preferIdAddress: true


