spring:
  application:
    name: service-registry-parcial


server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: false
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIdAddress: true
